# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [windows-2016]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
        
      - name: Setup 2013 Build tools
        run: choco install microsoft-build-tools-2013
#         run: choco install visualstudiocommunity2013
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Restore NuGet packages
        run: nuget restore AutoBuild2013.sln

      - name: Build the Solution
#         run: msbuild AutoBuild2013.sln /p:VisualStudioVersion=12.0
        shell: cmd
        run: |
          set
          set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120
          call "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" AutoBuild2013.sln /p:VisualStudioVersion=12.0
